---
- name: Ensure Debian based hosts are patched
  hosts: all
  serial: 1
  vars:
    skip_uncordon: false
  tasks:
    - name: Allow repository release info changes
      ansible.builtin.copy:
        content: 'Acquire::AllowReleaseInfoChange "true";'
        dest: /etc/apt/apt.conf.d/99allow-release-change
        mode: '0644'
      become: true
      when: (ansible_facts.os_family == 'Debian')

    - name: Ensures local repo cache is clear
      ansible.builtin.apt:
        autoclean: true
      become: true
      when: (ansible_facts.os_family == 'Debian')

    - name: Ensure unused dependencies are removed
      ansible.builtin.apt:
        autoremove: true
      become: true
      when: (ansible_facts.os_family == 'Debian')

    - name: Ensures repo cache is up to date
      ansible.builtin.apt:
        update_cache: true
      environment:
        DEBIAN_FRONTEND: noninteractive
      become: true
      when: (ansible_facts.os_family == 'Debian')

    - name: Ensures os is up to date
      ansible.builtin.apt:
        upgrade: true
      environment:
        DEBIAN_FRONTEND: noninteractive
      become: true
      when: (ansible_facts.os_family == 'Debian')

    - name: Check if a reboot is needed
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: file_check
      become: true
      when: (ansible_facts.os_family == 'Debian')

    - name: Reboot System
      block:
        - name: Drain node before a reboot
          kubernetes.core.k8s_drain:
            state: drain
            name: "{{ inventory_hostname }}"
            delete_options:
              delete_emptydir_data: true
              ignore_daemonsets: true
          timeout: 660
          register: drain_status
          delegate_to: "{{ k8s_control_node }}"
          when: groups['kubernetes'] is defined

        - name: Ensure Server is rebooted
          ansible.builtin.reboot:
            reboot_timeout: 3600
          become: true
          become_method: sudo

        - name: Wait for system connection
          ansible.builtin.wait_for_connection:
            delay: 60

        - name: Wait for node to report Ready status
          kubernetes.core.k8s_info:
            kind: Node
            name: "{{ inventory_hostname }}"
          delegate_to: "{{ k8s_control_node }}"
          register: node_info
          until:
            - node_info.resources[0].status.conditions | selectattr('type', 'equalto', 'Ready') | map(attribute='status') | first == 'True'
          retries: 30
          delay: 10
          when: groups['kubernetes'] is defined

        - name: Give pods a chance to start before continuing
          ansible.builtin.wait_for_connection:
            delay: 60
      rescue:
        - name: Drain node before a reboot
          kubernetes.core.k8s_drain:
            state: drain
            name: "{{ inventory_hostname }}"
          timeout: 660
          register: drain_status
          delegate_to: "{{ k8s_control_node }}"
          when: groups['kubernetes'] is defined

        - name: Set skip_uncordon
          ansible.builtin.set_fact:
            skip_uncordon: true
          when: groups['kubernetes'] is defined

      when:
        - file_check.stat.exists

    - name: Always ensure k8s nodes are uncondoned
      kubernetes.core.k8s_drain:
        state: uncordon
        name: "{{ inventory_hostname }}"
      delegate_to: "{{ k8s_control_node }}"
      register: uncordon_status
      when:
        (not skip_uncordon) and
        (groups['kubernetes'] is defined)

    - name: Give pods a chance to start before continuing
      ansible.builtin.wait_for_connection:
        delay: 60
      when: uncordon_status.changed
